### ISSUE TITLE
Apply a mixin to a specific package

### ISSUE THREAD

**Issue by allsey87** [colcon/colcon-mixin#41]
Is it currently possible to apply something like `cmake-args` to a specific package? For example, something like the following mixin, but with the `cmake-args` *only* applied to `package_to_apply_cmake_args` (the mixin below does not achieve this, it applies `cmake-args` to all packages).
```json
{
    "build": {
        "custom-mixin": {
            "packages-up-to": ["package_to_apply_cmake_args"],
            "cmake-args": [
                "-DBUILD_SHARED_LIBS=OFF"
            ]
        }
    }
}
```

**Comment by christophebedard** [comment]
I don't think so. For per-package options, you could use a [`colcon.pkg` file](https://colcon.readthedocs.io/en/released/user/configuration.html#colcon-pkg-files) or a [`.meta` file](https://colcon.readthedocs.io/en/released/user/configuration.html#meta-files), but it's not the same thing as using a mixin.

**Comment by allsey87** [comment]
Thanks @christophebedard, I will take a different approach then but will leave this issue open to be marked as a potential enhancement.

By the way, I really liked your implementation/blog on rmw_email, it helped me a fair bit when I was working on [ROS On Web](https://rosonweb.io).

**Comment by christophebedard** [comment]
> By the way, I really liked your implementation/blog on rmw_email, it helped me a fair bit when I was working on [ROS On Web](https://rosonweb.io).

Nice, good to hear it was useful!

**Comment by cottsay** [comment]
@christophebedard is right here - meta files are the recommended way to do something like adding cmake arguments for a specific package. There's no way to make a meta file apply to a set of packages though.

I think that either way, a PR to improve `colcon-metadata` would be the most likely path to landing a feature like this.
